name: Yarn build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '10' ]

    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn run build
      - run: yarn run build-types
      - run: yarn run test
